In [17]:
import pandas_datareader.data as web
from pandas_datareader.famafrench import get_available_datasets
import statsmodels.api as sm
import yfinance as yf

# 1. 下载 Fama-French 官方三因子数据
df_ff = web.DataReader('F-F_Research_Data_Factors', 'famafrench', start='2020-01-01')[0]
df_ff

         Mkt-RF   SMB    HML    RF
Date
2020-01   -0.11 -3.10  -6.22  0.13
2020-02   -8.15  1.08  -3.82  0.12
2020-03  -13.37 -4.69 -13.83  0.12
2020-04   13.60  2.50  -1.34  0.00
2020-05    5.57  2.40  -5.00  0.01
...         ...   ...    ...   ...
2025-07    1.98  0.26  -1.27  0.34
2025-08    1.84  3.87   4.42  0.38
2025-09    3.39 -1.85  -1.05  0.33
2025-10    1.96 -0.55  -3.09  0.37
2025-11   -0.13  0.38   3.76  0.30

[71 rows x 4 columns]

In [24]:
# 2. 下载单只股票收益率 (例如 AAPL)
stock_data = yf.download('AAPL', start='2020-01-01', progress=False, auto_adjust=True)['Close']
stock_ret = stock_data.pct_change().dropna() * 100 
stock_ret_monthly = (1 + stock_ret/100).resample('M').prod() - 1
stock_ret_monthly = stock_ret_monthly * 100 # 转回百分数
stock_ret_monthly.index = stock_ret_monthly.index.to_period('M')
stock_ret_monthly

Ticker        AAPL
Date
2020-01   3.049789
2020-02 -11.470146
2020-03  -6.976166
2020-04  15.537406
2020-05   8.509419
...            ...
2025-09   9.688125
2025-10   6.181514
2025-11   3.236426
2025-12  -2.506731
2026-01  -6.006764

[73 rows x 1 columns]

In [25]:
# 3. 合并数据并计算超额收益 (Return - Risk Free)
df_merge = pd.merge(stock_ret_monthly, df_ff, left_index=True, right_index=True)
df_merge.dropna(inplace=True)
df_merge.shape

(71, 5)

In [26]:
df_merge['Excess_Ret'] = df_merge['AAPL'] - df_merge['RF']

df_merge

              AAPL  Mkt-RF   SMB    HML    RF  Excess_Ret
Date
2020-01   3.049789   -0.11 -3.10  -6.22  0.13    2.919789
2020-02 -11.470146   -8.15  1.08  -3.82  0.12  -11.590146
2020-03  -6.976166  -13.37 -4.69 -13.83  0.12   -7.096166
2020-04  15.537406   13.60  2.50  -1.34  0.00   15.537406
2020-05   8.509419    5.57  2.40  -5.00  0.01    8.499419
...            ...     ...   ...    ...   ...         ...
2025-07   1.169770    1.98  0.26  -1.27  0.34    0.829770
2025-08  11.963886    1.84  3.87   4.42  0.38   11.583886
2025-09   9.688125    3.39 -1.85  -1.05  0.33    9.358125
2025-10   6.181514    1.96 -0.55  -3.09  0.37    5.811514
2025-11   3.236426   -0.13  0.38   3.76  0.30    2.936426

[71 rows x 6 columns]

In [27]:
# 4. 运行标准 Fama-French 时间序列回归
# Excess_Ret = alpha + b1*Mkt-RF + b2*SMB + b3*HML
X = df_merge[['Mkt-RF', 'SMB', 'HML']]
X = sm.add_constant(X)
model = sm.OLS(df_merge['Excess_Ret'], X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Excess_Ret   R-squared:                       0.562
Model:                            OLS   Adj. R-squared:                  0.542
Method:                 Least Squares   F-statistic:                     28.63
Date:                Mon, 19 Jan 2026   Prob (F-statistic):           4.97e-12
Time:                        16:30:51   Log-Likelihood:                -219.32
No. Observations:                  71   AIC:                             446.6
Df Residuals:                      67   BIC:                             455.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.7698      0.670      1.149      0.255      -0.568       2.107
Mkt-RF         1.1362      0.134      8.499      0.000       0.869       1.403
SMB           -0.0924      0.227     -0.407      0.685      -0.545       0.361
HML           -0.3950      0.146     -2.697      0.009      -0.687      -0.103
==============================================================================
Omnibus:                        0.252   Durbin-Watson:                   1.550
Prob(Omnibus):                  0.882   Jarque-Bera (JB):                0.049
Skew:                          -0.061   Prob(JB):                        0.976
Kurtosis:                       3.042   Cond. No.                         5.55
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

1. R-squared (0.562)： 决定系数。意味着 AAPL 收益率中 56.2% 的波动可以由模型中的因子（如市场、市值、账面市值比等）来解释。对于单只股票的月度数据，超过 50% 的解释力通常被认为是非常不错的。

2. Adj. R-squared (0.542)： 调整后的决定系数。它考虑了因子的数量。如果这个值和 R-squared 差距不大，说明你加入的因子都是有效的，没有无意义的堆砌。

3. F-statistic (28.63) & Prob (F-statistic) (4.97e-12)：
这个 P值（4.97e-12） 极其微小，远小于常见的显著性水平（0.05 或 0.01）。
结论： 这表明模型中的因子整体上对 AAPL 的收益率有显著的预测作用，模型不是乱凑的。

4. Log-Likelihood (-219.32)： 对数似然值。用于衡量模型拟合数据的程度，值越大越好（注意这是负数，所以 -219 比 -300 好）。

5. AIC (446.6) & BIC (455.7)： 信息准则指标。
这两个指标主要用于模型对比。如果你尝试了不同的模型（比如 CAPM vs Fama-French 三因子 vs 五因子），你应该选择 AIC 和 BIC 更小 的那个模型。
它们对模型的复杂程度（因子个数）进行了惩罚，防止过度拟合。

AAPL 是一只典型的“高贝塔、大盘成长股”，在这段时间里，AAPL 的走势主要受大盘波动和成长风格驱动，而小盘股效应和超额 Alpha 并不显著。
####################
1. Mkt-RF (市场风险因子)，coef=1.1362，P>|t|=0.000 (极显著)，高贝塔属性：系数大于 1，说明苹果比大盘更活泼。大盘涨 1%，苹果平均涨 1.14%。

2. HML (账面市值比因子)，coef=-0.3950，P>|t|=0.009 (显著)，成长股标签：系数为负且显著。说明 AAPL 与“价值股”背道而驰，是一只坚定的成长股。当市场热衷于炒作低估值价值股时，它往往表现较弱。

3. SMB (市值因子)，coef=-0.0924，P>|t|=0.685 (不显著)，大盘股特征：系数为负（符合其万亿市值身份），但 P 值很高。说明在 2020 年后的这段样本期内，市值大小并不是解释 AAPL 波动的主要矛盾。

4. const (Alpha / 截距项)，coef=0.7698，P>|t|=0.255 (不显著)，无显著超额收益：虽然月均 Alpha 约 0.77%，但统计上不显著。这意味着苹果这段时间的收益几乎能被上述三个风险因子完全解释，并没有表现出显著的“超能力”溢价。
####################
5. P 值 (P>|t|)：只有 Mkt-RF 和 HML 小于 0.05。这告诉我们，分析苹果时，你只需要重点关注大盘走势和成长/价值风格切换这两个维度，其他的因子在这段时期内基本是“统计噪音”。

6. 置信区间 ([0.025, 0.975])：
Mkt-RF 的区间 (0.869 至 1.403) 全部大于 0，说明其与大盘的正相关性极度稳固。
HML 的区间 (-0.687 至 -0.103) 全部小于 0，进一步确认了其成长股属性。
####################