本节主要介绍如何使用 Python 读取金融数据：

*原生Python 

*csv.reader

*pandas

pandas 在数据读取、处理、存储方面更高效。

In [13]:
# 如果下载失败，可以打开代理
# import os
# proxy = 'http://127.0.0.1:7897'
# os.environ['HTTP_PROXY'] = proxy 
# os.environ['HTTPS_PROXY'] = proxy 

import yfinance as yf

symbol = 'AAPL'
fn = 'AAPL.csv'

start_date = '2026-02-01'
end_date = '2026-03-01'

df = yf.download(symbol, start=start_date, end=end_date)

if not df.empty:
    df.to_csv(fn)
    print(f"数据已保存: {fn}")
else:
    print("数据获取失败")

[*********************100%***********************]  1 of 1 completed

数据已保存: AAPL.csv

In [14]:
# 用原生 Python 

with open(fn, 'r') as f:
    for _ in range(6):
        print(f.readline(), end='')

Price,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,
2026-02-02,269.7575988769531,270.2371306501278,258.9676766447768,259.7869174093499,73913400
2026-02-03,269.22808837890625,271.6258386480508,267.3598109321867,268.9483513556569,64394700
2026-02-04,276.23150634765625,278.68922850453845,272.03545112075,272.03545112075,90545700

In [15]:
# 使用 csv.reader

import csv
csv_reader = csv.reader(open(fn, 'r'))
data = list(csv_reader)
data[:6]

[['Price', 'Close', 'High', 'Low', 'Open', 'Volume'],
 ['Ticker', 'AAPL', 'AAPL', 'AAPL', 'AAPL', 'AAPL'],
 ['Date', '', '', '', '', ''],
 ['2026-02-02',
  '269.7575988769531',
  '270.2371306501278',
  '258.9676766447768',
  '259.7869174093499',
  '73913400'],
 ['2026-02-03',
  '269.22808837890625',
  '271.6258386480508',
  '267.3598109321867',
  '268.9483513556569',
  '64394700'],
 ['2026-02-04',
  '276.23150634765625',
  '278.68922850453845',
  '272.03545112075',
  '272.03545112075',
  '90545700']]

In [16]:
# 使用 csv.DictReader

csv_reader = csv.DictReader(open(fn, 'r'))
data = list(csv_reader)
data[:3]

[{'Price': 'Ticker',
  'Close': 'AAPL',
  'High': 'AAPL',
  'Low': 'AAPL',
  'Open': 'AAPL',
  'Volume': 'AAPL'},
 {'Price': 'Date',
  'Close': '',
  'High': '',
  'Low': '',
  'Open': '',
  'Volume': ''},
 {'Price': '2026-02-02',
  'Close': '269.7575988769531',
  'High': '270.2371306501278',
  'Low': '258.9676766447768',
  'Open': '259.7869174093499',
  'Volume': '73913400'}]

In [17]:
data_clean = data[2:]  # 跳过前两行
sum([float(l['Close']) for l in data_clean]) / len(data_clean)

269.1110133120888

In [37]:
# 使用 pandas

import pandas as pd
data = pd.read_csv(
    'AAPL.csv',
    skiprows=[1, 2],   # 跳过脏行
    index_col=0
)

# 突出金融数据的时间序列属性，体现pandas的优势
data.index = pd.to_datetime(data.index)
data.sort_index(inplace=True)

data.head()

                 Close        High         Low        Open    Volume
Price
2026-02-02  269.757599  270.237131  258.967677  259.786917  73913400
2026-02-03  269.228088  271.625839  267.359811  268.948351  64394700
2026-02-04  276.231506  278.689229  272.035451  272.035451  90545700
2026-02-05  275.652069  279.238709  272.974582  277.869995  52977400
2026-02-06  277.859985  280.647386  276.671095  276.860920  50453400

In [38]:
data['Close'].mean()

269.1110133120888

In [35]:
data.dtypes

Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [27]:
# !pip install openpyxl

In [30]:
data.to_excel('aapl.xlsx', sheet_name='AAPL')
data.to_json('aapl.json')

In [31]:
data_copy_1 = pd.read_excel('aapl.xlsx', sheet_name='AAPL', index_col=0)
data_copy_1.head()

                 Close        High         Low        Open    Volume
Price
2026-02-02  269.757599  270.237131  258.967677  259.786917  73913400
2026-02-03  269.228088  271.625839  267.359811  268.948351  64394700
2026-02-04  276.231506  278.689229  272.035451  272.035451  90545700
2026-02-05  275.652069  279.238709  272.974582  277.869995  52977400
2026-02-06  277.859985  280.647386  276.671095  276.860920  50453400

In [33]:
data_copy_2 = pd.read_json('aapl.json')
data_copy_2.head()

                 Close        High         Low        Open    Volume
2026-02-02  269.757599  270.237131  258.967677  259.786917  73913400
2026-02-03  269.228088  271.625839  267.359811  268.948351  64394700
2026-02-04  276.231506  278.689229  272.035451  272.035451  90545700
2026-02-05  275.652069  279.238709  272.974582  277.869995  52977400
2026-02-06  277.859985  280.647386  276.671095  276.860920  50453400

本节对比了三种数据读取方式：

*原生 Python：只能读，不能分析

*csv 模块：结构稍好，但操作繁琐

*pandas：结构清晰，计算高效

实际金融数据往往包含脏数据（如多余表头），需要清洗后才能使用。pandas 通过 DataFrame 提供统一结构，并天然支持时间序列处理（索引、排序、滚动计算等）。